### PR TITLE
Bump tar version

### PR DESCRIPTION
**Pull request by SiegfriedEhret**
Fix https://github.com/ForbesLindesay/tar-pack/issues/6

### CODE REVIEW

**Comment by SiegfriedEhret** [comment]
Weird, getting some error here: https://travis-ci.org/ForbesLindesay/tar-pack/jobs/88966016

```
npm ERR! Error: No compatible version found: fstream@'^1.0.2'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.0.1","0.1.0","0.1.1","0.1.2","0.1.3","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.1.11","0.1.12","0.1.13","0.1.14","0.1.15","0.1.16","0.1.17","0.1.18","0.1.19","0.1.20","0.1.21","0.1.22","0.1.23","0.1.24","0.1.25","0.1.26","0.1.27","0.1.28","0.1.29","0.1.30","1.0.0","1.0.1","0.1.31","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7","1.0.8"]
npm ERR!     at installTargetsError (/home/siegfried/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/siegfried/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at RegClient.get_ (/home/siegfried/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/home/siegfried/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.readFile (fs.js:181:14)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.2.4-1-ARCH
npm ERR! command "/home/siegfried/.nvm/v0.8.28/bin/node" "/home/siegfried/.nvm/v0.8.28/bin/npm" "i"
npm ERR! cwd /home/siegfried/dev/tar-pack
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
```

**Comment by SiegfriedEhret** [comment]
@ForbesLindesay silly question: do we really need node 0.8 ?

**Comment by ForbesLindesay** [comment]
Unfortunately, yes.  We need 0.8 until it stops being supported by npm.

**Comment by shinnn** [comment]
This pull request will pass the test after https://github.com/ForbesLindesay/tar-pack/pull/8 is merged, with keeping Node v0.8 support.

**Comment by SiegfriedEhret** [comment]
:trophy: @shinnn !

**Comment by ForbesLindesay** [comment]
Would you like to be added as a collaborator on this project, to help review and merge pull requests?

**Pull request merged**
