### PR TITLE
Update fstream & tar dependencies to latest

### LINKED ISSUE #9: Outdated dependencies causing npm conflicts
https://github.com/strongloop/fsevents/issues/100

Specifically aggravated by npm3 dependency flattening

PR incoming to update a few deps that would resolve the issue.

### PR DESCRIPTION
**Pull request by es128**
Resolves #9

Tests continue to pass locally with the updates

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
This now needs a rebase.

**Comment by es128** [comment]
rebased

**Comment by ForbesLindesay** [comment]
Would you like to be added as a collaborator on this project, to help review and merge pull requests?

**Comment by es128** [comment]
Thanks for the offer. I suppose it couldn't hurt. 

I haven't used this module directly, but happy to help where I can.

**Comment by ForbesLindesay** [comment]
Thanks, you're added. Please follow these rules:

1. never commit directly to master unless you're only editing documentation, or you're in the process of cutting a new release.
2. never merge your own pull request unless it's had no comments from any collaborators for at least 24 hours.
3. If you cut a new release, make sure you follow [semver](http://semver.org/) when updating the version number.

If you let me know your npm username I'll add you as an owner so you can release new versions :)

**Comment by es128** [comment]
Thanks. Same name on npm: es128

**Comment by ForbesLindesay** [comment]
Thanks. I've added you as an owner :)

**Pull request merged**
